# Generated by Django 3.1 on 2020-08-16 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestType', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(default='')),
                ('Link', models.TextField(default='')),
                ('PubDate', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.TextField(default=1)),
                ('StateCode', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusType', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestDesc', models.TextField(default='')),
                ('City', models.TextField(default='')),
                ('Pincode', models.IntegerField(default=0)),
                ('PhoneCode', models.TextField(default='')),
                ('Phone', models.IntegerField(default='')),
                ('Remark', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('RequestType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRequest_type', to='Request_app.requesttypemaster')),
                ('RequestedUser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='UserRequest_user', to=settings.AUTH_USER_MODEL)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRequest_state', to='Request_app.statemaster')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRequest_Status', to='Request_app.statusmaster')),
            ],
        ),
    ]
